<?php
/**
 * Copyright © 2016 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile
$block->setPriceModel();
$prices = $block->getPricesWithDiscount();
$cart_subtotal = $block->getCartSubtotal();
?>

<?php
/** @var \Magento\Catalog\Pricing\Render\FinalPriceBox $block */

$productId = $block->getSaleableItem()->getId();

/** ex: \Magento\Catalog\Pricing\Price\RegularPrice */
/** @var \Magento\Framework\Pricing\Price\PriceInterface $priceModel */
$priceModel = $block->getPriceType('regular_price');

/** ex: \Magento\Catalog\Pricing\Price\FinalPrice */
/** @var \Magento\Framework\Pricing\Price\PriceInterface $finalPriceModel */
$finalPriceModel = $block->getPriceType('final_price');
$idSuffix = $block->getIdSuffix() ? $block->getIdSuffix() : '';
$schema = ($block->getZone() == 'item_view') ? true : false;

if(count($prices) > 0){  //create string with all price breakpoints, that can be parsed via js in addtocart.phtml
    $additionalPrices = '0';
    foreach($prices as $p){
        $additionalPrices = $additionalPrices.'/'.$p['quantity'];
    }
}
$hasActivePrice = false;

?>
<?php if ($block->hasSpecialPrice()): ?>
    <?php /* @escapeNotVerified */ echo $block->renderAmount($finalPriceModel->getAmount(), [
        'display_label'     => __('Current Price:'),
        'price_id'          => 'finalPrice',
        'price_type'        => 'finalPrice',
        'include_container' => true,
        'schema' => $schema
    ]); ?>
    <?php if(count($prices) > 1):?>
        <h4 class="price-title"><?=__('Price for:')?></h4>
    <?php endif;?>
    <div class="additional-price-wrap" data-pices="<?=$additionalPrices?>">
        <?php if(count($prices) > 0):?>
            <?php foreach($prices as $p):?>
                <?php if($p['active'] == 1){
                    $hasActivePrice = true;
                }?>
                <?php
                if($p['max_price'] < $p['price']){continue;}
                if($p['max_price'] < $cart_subtotal){continue;}
                ?>
                <div class="price-container additional-price" data-qty="<?=($p['active'] > 0)?1:$p['quantity']?>">
                    <span class="price-main-info">
                        <?php //if($p['label_in']):?>
                        <?=$p['label']?>:
                        <?php //endif;?>
                        <span class="price-wrapper id-<?=$p['quantity']?> <?=($p['active'] > 0)?'active':'';?>">
                            <?=$p['discount_price_text']?>
                        </span>
                    </span>
                    <?php if($p['label_in']):?>
                        <?php if($p['active'] > 0):?>
                            <span class="price-qty"> 1 <span class="price-qty-title"><?=__('piece')?></span></span>
                        <?php else:?>
                            <span class="price-qty"> <?=$p['quantity']?> <span class="price-qty-title"><?=($p['quantity'] >1)?__('pieces'):__('piece')?></span></span>
                        <?php endif;?>
                        <?php if($p['message'] != ''):?>
                            <div class="price-decsription" data-mage-init='{"priceTooltip":{"message":".price-message"}}'>
                                <span class="price-info-icon"></span>
                                <span class="message-arrow"></span>
                                <p class="price-message">
                                    <?=__($p['message'])?>
                                </p>
                            </div>
                        <?php endif;?>
                    <?php endif;?>
                </div>
            <?php endforeach;?>
        <?php else:?>
            <div class="special-price">
                <?php /* @escapeNotVerified */ echo $block->renderAmount($finalPriceModel->getAmount(), [
                    'display_label'     => __('Special Price'),
                    'price_id'          => $block->getPriceId('product-price-' . $idSuffix),
                    'price_type'        => 'finalPrice',
                    'include_container' => true,
                    'schema' => $schema
                ]); ?>
            </div>
        <?php endif;?>

<!--        <div class="old-price">-->
            <?php /* @escapeNotVerified */ /*echo $block->renderAmount($priceModel->getAmount(), [
                'display_label'     => __('Old Price'),
                'price_id'          => $block->getPriceId('old-price-' . $idSuffix),
                'price_type'        => 'oldPrice',
                'include_container' => true,
                'skip_adjustments'  => true
            ]);*/ ?>
<!--        </div>-->
    </div>
<?php else: ?>
    <?php /* @escapeNotVerified */ echo $block->renderAmount($finalPriceModel->getAmount(), [

        'display_label'     => __('Current Price:'),
        'price_id'          => 'finalPrice',
        'price_type'        => 'finalPrice',
        'include_container' => true,
        'schema' => $schema
    ]); ?>
    <?php if(count($prices) > 1):?>
        <h4 class="price-title"><?=__('Price for')?>:</h4>
    <?php endif;?>
    <?php if(count($prices) > 0):?>
        <div class="additional-price-wrap" data-pices="<?=$additionalPrices?>">
            <?php foreach($prices as $p):?>
                <?php if($p['active'] == 1){
                    $hasActivePrice = true;
                }?>

                <?php
                    if($p['max_price'] < $p['price']){continue;}
                    if($p['max_price'] < $cart_subtotal){continue;}
                ?>
                <div class="price-container additional-price" data-qty="<?=($p['active'] > 0)?1:$p['quantity']?>">
                    <span class="price-main-info">
                        <?php //if($p['label_in']):?>
                            <?=$p['label']?>:
                        <?php //endif;?>
                        <span class="price-wrapper id-<?=$p['quantity']?> <?=($p['active'] > 0)?'active':'';?>">
                            <?=$p['discount_price_text']?>
                        </span>
                    </span>
                    <?php if($p['label_in']):?>
                        <?php if($p['active'] > 0):?>
                            <span class="price-qty"> 1 <span class="price-qty-title"><?=__('piece')?></span></span>
                        <?php else:?>
                            <span class="price-qty"> <?=$p['quantity']?> <span class="price-qty-title"><?=($p['quantity'] >1)?__('pieces'):__('piece')?></span></span>
                        <?php endif;?>
                        <?php if($p['message'] != ''):?>
                            <div class="price-decsription" data-mage-init='{"priceTooltip":{"message":".price-message"}}'>
                                <span class="price-info-icon"></span>
                                <span class="message-arrow"></span>
                                <p class="price-message">
                                    <?=__($p['message'])?>
                                </p>
                            </div>
                        <?php endif;?>
                    <?php endif;?>
                </div>
            <?php endforeach;?>
        </div>
    <?php else:?>
            <?php /* @escapeNotVerified */ echo $block->renderAmount($finalPriceModel->getAmount(), [
                'price_id'          => $block->getPriceId('product-price-' . $idSuffix),
                'price_type'        => 'finalPrice',
                'include_container' => true,
                'schema' => $schema
            ]); ?>
    <?php endif;?>

<?php endif; ?>

<?php if ($block->showMinimalPrice()): ?>
    <?php if ($block->getUseLinkForAsLowAs()):?>
        <a href="<?php /* @escapeNotVerified */ echo $block->getSaleableItem()->getProductUrl(); ?>" class="minimal-price-link">
            <?php /* @escapeNotVerified */ echo $block->renderAmountMinimal(); ?>
        </a>
    <?php else:?>
        <span class="minimal-price-link">
            <?php /* @escapeNotVerified */ echo $block->renderAmountMinimal(); ?>
        </span>
    <?php endif?>
<?php endif; ?>

<?php if(!$hasActivePrice):?>
<script>
    document.querySelector('.price-box>.price-container .price-wrapper:not(.active)').className += ' active';
</script>
<?php endif; ?>