<div class="social-links-wrap">
    <a class="facebook" href="https://www.facebook.com/"><span>facebook</span></a>
    <a class="twitter" href="https://twitter.com/"><span>twitter</span></a>
    <a class="google-plus" href="https://plus.google.com/"><span>google-plus</span></a>
    <a class="instagram" href="https://www.instagram.com/"><span>instagram</span></a>
    <a class="linkedin" href="https://www.linkedin.com/"><span>linkedin</span></a>
</div>